In [1]:
import pathlib
import os
if not "changed_working_directory" in locals():
    changed_working_directory = True
    os.chdir(pathlib.Path().resolve().parent)
%load_ext autoreload
%autoreload 2

In [2]:
import tensorflow as tf
import tensorflow_probability as tfp

In [152]:
x = tf.Variable(1.)
logits = tf.Variable(0.)

with tf.GradientTape(persistent=True) as tape:
    b = tfp.distributions.Bernoulli(logits=logits, dtype=tf.float32).sample()
    print(b)
    y = x**2 * b
dy_dx = tape.gradient(y, x)
dy_dx

tf.Tensor(0.0, shape=(), dtype=float32)


<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [151]:
dy_dlogits = tape.gradient(y, logits)
dy_dlogits

In [35]:
import numpy as np
probs = tf.Variable([[.5, .5]])
with tf.GradientTape(persistent=True) as tape:
  sample = tfp.distributions.ExpRelaxedOneHotCategorical(probs=probs, temperature=[.2, 1., 5]).sample()
  sample1 = tf.math.exp(sample)
  sample2 = tfp.distributions.RelaxedOneHotCategorical(probs=probs, temperature=[.2, 1., 5]).sample()
print(tape.gradient(sample, probs).numpy(),'\n')
print(sample1.numpy(), sample, tape.gradient(sample1, probs).numpy(),'\n')
print(sample2.numpy(), np.log(sample2), tape.gradient(sample2, probs).numpy(),'\n')

[[ 9.731071 -9.731071]] 

[[0.01288797 0.987112  ]
 [0.48840317 0.5115969 ]
 [0.57194513 0.4280549 ]] tf.Tensor(
[[-4.351461   -0.01297178]
 [-0.71661407 -0.6702183 ]
 [-0.55871224 -0.8485038 ]], shape=(3, 2), dtype=float32) [[-1.09896064e-07  4.76837158e-07]] 

[[9.99987721e-01 1.22596002e-05]
 [1.00230336e-01 8.99769604e-01]
 [3.66007984e-01 6.33991957e-01]] [[-1.2278632e-05 -1.1309201e+01]
 [-2.3002844e+00 -1.0561654e-01]
 [-1.0051001e+00 -4.5571902e-01]] [[2.6822089e-08 1.4305115e-07]] 



In [138]:
logits = tf.Variable([0.5, 0.5])
with tf.GradientTape(persistent=True) as tape:
    sample = tfp.distributions.RelaxedOneHotCategorical(probs=logits, temperature=1).sample()
    sample2 = tf.nn.softmax(logits)
    print("Gumbel sample:", sample)
    print("Softmax applied:", sample2)
    loss = sample[1]
    loss2 = sample2[1]
print(tape.gradient(sample, logits))
print("Gumbel:", tape.gradient(loss, logits))
print("Softmax:", tape.gradient(loss2, logits))

Gumbel sample: tf.Tensor([0.24288398 0.757116  ], shape=(2,), dtype=float32)
Softmax applied: tf.Tensor([0.5 0.5], shape=(2,), dtype=float32)
tf.Tensor([0. 0.], shape=(2,), dtype=float32)
Gumbel: tf.Tensor([-0.3677827  0.3677827], shape=(2,), dtype=float32)
Softmax: tf.Tensor([-0.25  0.25], shape=(2,), dtype=float32)


SVC(probability=True)

SVC(probability=True)